name: Deploy Server

on:
  pull_request:
    types:
      - closed
     
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps: 
    - uses: actions/checkout@v3
    - name: Login
      uses: docker/login-action@v2
      with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}   
    - name: Build image
      run:  docker build .
            --file Dockerfile
            --tag ${{ secrets.DOCKERHUB_USERNAME }}/simple_server:${{ github.sha }}
    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple_server:${{ github.sha }}

      
      

        


              
