name: Deploy Server

on: workflow_dispatch
  # pull_request:
  #   types:
  #     - closed

      
jobs:
  deploy:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - run: echo "Gello"

      
      

        


              
