name: Server Deployment

on:  push

# jobs:
#     test:
#         name: Testing server
#         runs-on: ubuntu-latest
#         steps:
#             - uses: actions/checkout@v3
#             - name: Set up python
#               uses: actions/setup-python@v4
#               with:
#                 python-version: 3.11
#             - name: Display Python version
#               run: python -c "import sys; print(sys.version)"

#             - name: Install dependencies
#               run: |
#                 python -m pip install --upgrade pip
#                 pip install flake8
#                 pip install requests
#                 pip install coverage

#             - name: Test main
#               run: python3 -m unittest test.py
#             - name: Analysing the code with pylint
#               run: flake8 . --max-line-length=100
            
#             - name: coverage
#               run: |
#                 python3 -m coverage run --source . -m unittest test.py
#                 python3 -m coverage html
            
#             - name: Upload artifacts
#               uses: actions/upload-artifact@v3
#               with:
#                 name: coverage
#                 path: htmlcov

#     docker_hub:
#         name: Build Docker Image
#         needs: [test]
#         runs-on: ubuntu-latest
#         steps: 
#             - uses: actions/checkout@v3
#             - name: Login
#               uses: docker/login-action@v2
#               with:
#                 username: ${{ secrets.DOCKERHUB_USERNAME }}
#                 password: ${{ secrets.DOCKERHUB_TOKEN }}   
#             - name: Build image
#               run:  docker build .
#                     --file Dockerfile
#                     --tag ${{ secrets.DOCKERHUB_USERNAME }}/simple_server:${{ github.sha }}
#             - name: Push image to Docker Hub
#               run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/simple_server:${{ github.sha }}
#             - run: echo ${{ github.sha }}
jobs:
    deploy:
        name: Deploy server
        #needs: [docker_hub]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - name: Deploy on VPS
              uses: appleboy/ssh-action@master
              with:
                host: ${{ secrets.SSH_HOST }}
                username: ${{ secrets.SSH_USER }}
                password: ${{ secrets.SSH_KEY }}
                script: echo 'hello world'
                    # docker pull ${{ secrets.DOCKERHUB_USERNAME }}/simple_server:${{ github.sha }} &&
                    # docker stop python_server &&
                    # docker run  --name python_server 
                    #             -p 3000:3000 
                    #             -d --rm
                    #             ${{ secrets.DOCKERHUB_USERNAME }}/simple_server:${{ github.sha }}

    